"""
populate.py
Lê a ontologia base (music.ttl) e os 5 ficheiros JSON, e produz UM único
ficheiro Turtle completo (musica_portuguesa.ttl) que contém:
  - A TBox (classes, propriedades, restrições) — copiada da ontologia
  - A ABox (indivíduos) — gerada a partir dos JSONs

Estrutura assumida:
    projeto/
    ├── music.ttl
    ├── datasets/
    │   ├── editoras.json
    │   ├── artistas.json
    │   ├── bandas.json
    │   ├── albuns.json
    │   └── musicas.json
    └── scripts/
        └── populate.py    ← corre a partir daqui

Sobre os géneros:
  Os géneros (Fado, Pop, Rock, etc.) ficam declarados APENAS como classes.
  Para os usar em :pertenceAoGenero gera-se a tripla directamente sem os
  declarar como NamedIndividual — é punning implícito em OWL 2.
  Resultado: as queries `?m :pertenceAoGenero :Fado` funcionam, e os géneros
  só aparecem no separador "Classes" do Protégé.
"""
import json

ONTOLOGIA = 'music.ttl'
DATASETS  = '../datasets/'
OUTPUT    = 'musica_portuguesa.ttl'


def esc(s):
    return s.replace('\\', '\\\\').replace('"', '\\"')

def carregar(ficheiro):
    with open(DATASETS + ficheiro, encoding='utf-8') as f:
        return json.load(f)

def secao(titulo):
    return (
        "\n#################################################################\n"
        f"#    {titulo}\n"
        "#################################################################\n\n"
    )


# ─── Geradores por tipo de entidade ──────────────────────────────────

def gerar_editora(e):
    linhas = [f":{e['id']} a :Editora, owl:NamedIndividual"]
    linhas.append(f':nome "{esc(e["nome"])}"')
    return ' ;\n    '.join(linhas) + ' .\n\n'

def gerar_artista_solo(a):
    linhas = [f":{a['id']} a :ArtistaSolo, owl:NamedIndividual"]
    linhas.append(f':nome "{esc(a["nome"])}"')
    if 'anoNascimento' in a:
        linhas.append(f':anoNascimento {a["anoNascimento"]}')
    if 'pertenceAEditora' in a:
        linhas.append(f':pertenceAEditora :{a["pertenceAEditora"]}')
    for g in a.get('generos', []):
        linhas.append(f':pertenceAoGenero :{g}')
    return ' ;\n    '.join(linhas) + ' .\n\n'

def gerar_banda(b):
    linhas = [f":{b['id']} a :Banda, owl:NamedIndividual"]
    linhas.append(f':nome "{esc(b["nome"])}"')
    if 'anoFormacao' in b:
        linhas.append(f':anoFormacao {b["anoFormacao"]}')
    if 'pertenceAEditora' in b:
        linhas.append(f':pertenceAEditora :{b["pertenceAEditora"]}')
    for g in b.get('generos', []):
        linhas.append(f':pertenceAoGenero :{g}')
    for m in b.get('temMembro', []):
        linhas.append(f':temMembro :{m}')
    return ' ;\n    '.join(linhas) + ' .\n\n'

def gerar_album(a):
    linhas = [f":{a['id']} a :Album, owl:NamedIndividual"]
    linhas.append(f':nome "{esc(a["nome"])}"')
    if 'anoLancamento' in a:
        linhas.append(f':anoLancamento {a["anoLancamento"]}')
    for g in a.get('generos', []):
        linhas.append(f':pertenceAoGenero :{g}')
    bloco = ' ;\n    '.join(linhas) + ' .\n'
    if 'lancadoPor' in a:
        bloco += f":{a['lancadoPor']} :lancouAlbum :{a['id']} .\n"
    return bloco + '\n'

def gerar_musica(m):
    linhas = [f":{m['id']} a :Musica, owl:NamedIndividual"]
    linhas.append(f':nome "{esc(m["nome"])}"')
    for ip in m.get('interpretadaPor', []):
        linhas.append(f':interpretadaPor :{ip}')
    for cp in m.get('compostaPor', []):
        linhas.append(f':compostaPor :{cp}')
    for ep in m.get('escritaPor', []):
        linhas.append(f':escritaPor :{ep}')
    if 'pertenceAoAlbum' in m:
        linhas.append(f':pertenceAoAlbum :{m["pertenceAoAlbum"]}')
    for g in m.get('generos', []):
        linhas.append(f':pertenceAoGenero :{g}')
    return ' ;\n    '.join(linhas) + ' .\n\n'


# ─── Orquestração ────────────────────────────────────────────────────

def main():
    print(f"A ler a ontologia base ({ONTOLOGIA})...")
    with open(ONTOLOGIA, encoding='utf-8') as f:
        ontologia = f.read()

    marcador = "###  Generated by the OWL API"
    if marcador in ontologia:
        ontologia = ontologia[:ontologia.index(marcador)].rstrip() + '\n'

    print("A carregar os ficheiros JSON...")
    editoras = carregar('editoras.json')['editoras']
    artistas = carregar('artistas.json')['artistasSolo']
    bandas   = carregar('bandas.json')['bandas']
    albuns   = carregar('albuns.json')['albuns']
    musicas  = carregar('musicas.json')['musicas']

    abox = secao("INDIVÍDUOS (gerado por populate.py)")

    abox += secao("Editoras")
    for e in editoras:
        abox += gerar_editora(e)

    abox += secao("Artistas Solo")
    for a in artistas:
        abox += gerar_artista_solo(a)

    abox += secao("Bandas")
    for b in bandas:
        abox += gerar_banda(b)

    abox += secao("Albuns")
    for a in albuns:
        abox += gerar_album(a)

    abox += secao("Musicas")
    for m in musicas:
        abox += gerar_musica(m)

    with open(OUTPUT, 'w', encoding='utf-8') as f:
        f.write(ontologia)
        f.write(abox)

    print(f"\n✓ {OUTPUT} gerado (ontologia + indivíduos)")
    print(f"  - {len(editoras)} editoras")
    print(f"  - {len(artistas)} artistas solo")
    print(f"  - {len(bandas)} bandas")
    print(f"  - {len(albuns)} álbuns")
    print(f"  - {len(musicas)} músicas")


if __name__ == "__main__":
    main()